PLTF-11: Доработка PoemsAPI №1
SwatAssault/platform pull request #9
Opened 2023-06-22 15:35 UTC by dimatovs

Реализовать новый эндпоинт (гет запрос) "/poems/authors-and-poems", выполняющий следующую функцию:
-берет всех авторов
-исключает всех авторов, у которых имя начинается с букв В и С
-формирует по каждому автору объект из полей: имя автора, кол-во его стихов (кол-во - рандомно сгенерированное число от 0 до 100)

2023-06-22 15:45 UTC, SwatAssault requested changes
общее замечание: форматирование

2023-06-22 15:45 UTC, SwatAssault commented on poems/src/main/java/com/project/poems/controller/PoemsController.java
> +   @GetMapping("/authors-and-poems")
не хватает пустой строки

2023-06-22 15:45 UTC, SwatAssault commented on poems/src/main/java/com/project/poems/controller/PoemsController.java
> +       Stream stream = authors.getAuthors().stream();
то, что ты добрался до стримов уже хорошо
но работать с ними надо проще
1. не надо создавать отдельно стрим и сохранять его. Все преобразования над коллекцией с помощью стрима не должны возвращать обратно стрим. В твоем случае должны возвращать обратно коллекцию
2. используй вместо charAt() startsWith() - метод стринг

2023-06-22 15:45 UTC, SwatAssault commented on poems/src/main/java/com/project/poems/controller/PoemsController.java
> +       if (authors != null) {
зачем здесь эта проверка? что она дает?

2023-06-23 15:50 UTC, SwatAssault requested changes
вынеси сразу в рамках этой задачи логику в сервис

2023-06-23 15:50 UTC, SwatAssault commented on poems/src/main/java/com/project/poems/dto/AuthorStats.java
> +    private String authors;
почему множественное число?

2023-06-23 15:50 UTC, SwatAssault commented on poems/src/main/java/com/project/poems/dto/AuthorStats.java
> +    private int stats;
что такое инт статс? что значит число статс?

2023-06-23 15:50 UTC, SwatAssault commented on poems/src/main/java/com/project/poems/controller/PoemsController.java
> +       for (AuthorStats point : authorsList) {
почему point......

2023-06-23 15:50 UTC, SwatAssault commented on poems/src/main/java/com/project/poems/controller/PoemsController.java
> +       List<AuthorStats> authorsList = authors.getAuthors().stream()
переменную уже имеет смысл назвать по-другому, например, statistics

2023-06-23 18:48 UTC, dimatovs commented on poems/src/main/java/com/project/poems/controller/PoemsController.java
> +   @GetMapping("/authors-and-poems")
Между методами нужно две пустые строки?

2023-06-23 20:20 UTC, SwatAssault requested changes

2023-06-23 20:20 UTC, SwatAssault commented on poems/src/main/java/com/project/poems/dto/AuthorStats.java
> +    public AuthorStats(String authors, int poemsNumber) {
а в кострукторе осталось по старому

2023-06-25 10:54 UTC, SwatAssault approved these changes

2023-06-25 10:54 UTC, merged